spring.application.name=PokerPulse

spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.username=postgres
spring.datasource.password=Rzymek13!

spring.sql.init.mode=always








#spring.docker.compose.lifecycle-management=start_and_stop



#spring.datasource.url=${postgres-url}
#spring.datasource.username=${postgres-username}
#spring.datasource.password=${postgres-password}
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.cloud.azure.keyvault.secret.endpoint=https://poker-app-kv.vault.azure.net/




#logging.level.org.springframework=DEBUG

# Initialize schema.sql on startup
#spring.sql.init.mode=always

# Logging (optional)
# logging.level.org.springframework.jdbc.core=DEBUG
